// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoYPoccEuZfCD6vcNSipdoE9pDtryeVF8',
    appId: '1:189151766931:web:b8258feed5afa86594e066',
    messagingSenderId: '189151766931',
    projectId: 'pruebatec-e0e08',
    authDomain: 'pruebatec-e0e08.firebaseapp.com',
    storageBucket: 'pruebatec-e0e08.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbgg8fBHTsxnk9JQSIes8-qZOkjV8kkC0',
    appId: '1:189151766931:android:f48089332070349294e066',
    messagingSenderId: '189151766931',
    projectId: 'pruebatec-e0e08',
    storageBucket: 'pruebatec-e0e08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9zWXVSPUP-TjrzhhMLUXOyeAhkfulr24',
    appId: '1:189151766931:ios:3a6ee025876b53c794e066',
    messagingSenderId: '189151766931',
    projectId: 'pruebatec-e0e08',
    storageBucket: 'pruebatec-e0e08.appspot.com',
    iosBundleId: 'com.example.pruebaTecnica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9zWXVSPUP-TjrzhhMLUXOyeAhkfulr24',
    appId: '1:189151766931:ios:a431f0bc024ab64b94e066',
    messagingSenderId: '189151766931',
    projectId: 'pruebatec-e0e08',
    storageBucket: 'pruebatec-e0e08.appspot.com',
    iosBundleId: 'com.example.pruebaTecnica.RunnerTests',
  );
}
